### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by vijaydaniel** [vorburger/opendaylight-etcd#2]
Hi Michael,
I tried to build it with the ODL settings.xml file, but getting the blow error.

[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for org.opendaylight.etcd:test-model:0.0.1-SNAPSHOT: Could not find artifact org.opendaylight.mdsal:binding-parent:pom:0.13.0-SNAPSHOT in opendaylight-snapshot (https://nexus.opendaylight.org/content/repositories/opendaylight.snapshot/) and 'parent.relativePath' points at no local POM @ line 5, column 11
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project org.opendaylight.etcd:test-model:0.0.1-SNAPSHOT (C:\etcd\opendaylight-etcd\test-model\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.opendaylight.etcd:test-model:0.0.1-SNAPSHOT: Could not find artifact org.opendaylight.mdsal:binding-parent:pom:0.13.0-SNAPSHOT in opendaylight-snapshot (https://nexus.opendaylight.org/content/repositories/opendaylight.snapshot/) and 'parent.relativePath' points at no local POM @ line 5, column 11 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

**Comment by vorburger** [comment]
@vijaydaniel first of all, thanks for your interest in the project - looking forward to your contributions! :smile: 

The problem you hit above seems to be fixed by @jveverka in #3 - watch that?

Just open new issues once you are past above if you hit other problems.
